/* Generated by Cython 0.29.35 */

#ifndef __PYX_HAVE__ml_pdf_cape
#define __PYX_HAVE__ml_pdf_cape

#include "Python.h"

#ifndef __PYX_HAVE_API__ml_pdf_cape

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void python_init(void);
__PYX_EXTERN_C double *calc_trigger(int, int, double **, double **, double **);

#endif /* !__PYX_HAVE_API__ml_pdf_cape */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initml_pdf_cape(void);
#else
PyMODINIT_FUNC PyInit_ml_pdf_cape(void);
#endif

#endif /* !__PYX_HAVE__ml_pdf_cape */
